version: '2'
services:
  app1:
    image: miapache
    container_name: apache1
    volumes:
      - ./index.html:/var/www/html/index.php:ro  
    networks:
      - tanet
  app2:
    image: miapache
    container_name: apache2
    networks:
      - tanet
    volumes:
      - ./index2.html:/var/www/html/index.php:ro  
  nginx:
    image: nginx:alpine
    container_name: rproxyb
    volumes:
      - ./nginx3.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - tanet
    ports:
      - "99:80"
networks:
  tanet:
    driver: bridge